### ISSUE TITLE
grpc web support

### ISSUE THREAD

**Issue by zezo357** [socotecio/django-socio-grpc#120]
I want to acess grpc endpoint from web but a proxy is needed 

while i found this package [sonora](https://github.com/public/sonora) to make grpc and grpc web endpoints work on apps

but i cant find a way to use it with your package

**Comment by AMontagu** [comment]
Hello @zezo357

We do not have documentation or tested sonora or any python native proxy yet. We are open to pull request. 
Yet it should work just by calling the  grpc_settings.ROOT_HANDLERS_HOOK methods with as parameter the sonora application instead of the grpc server.

Be aware that if you want both grpc support and proxy support you will still need 2 servers running (one with uwsgi or asgi and one with grpc server).

Here is the link to the call of ROOT_HANDLERS_HOOK: https://github.com/socotecio/django-socio-grpc/blob/master/django_socio_grpc/management/commands/grpcrunaioserver.py#L82

ROOT_HANDLERS_HOOK is just a path to a method that register your grpc service: https://github.com/socotecio/django-socio-grpc/blob/master/django_socio_grpc/settings.py#L6

Please if you try it let me know if it worked. I will still recommend everyone to use a envoy based proxy for performance matter but having multiple choice is always a good thing.

**Comment by zezo357** [comment]
> Hello @zezo357
> 
> We do not have documentation or tested sonora or any python native proxy yet. We are open to pull request. 
> Yet it should work just by calling the  grpc_settings.ROOT_HANDLERS_HOOK methods with as parameter the sonora application instead of the grpc server.
> 
> Be aware that if you want both grpc support and proxy support you will still need 2 servers running (one with uwsgi or asgi and one with grpc server).
> 
> Here is the link to the call of ROOT_HANDLERS_HOOK: https://github.com/socotecio/django-socio-grpc/blob/master/django_socio_grpc/management/commands/grpcrunaioserver.py#L82
> 
> ROOT_HANDLERS_HOOK is just a path to a method that register your grpc service: https://github.com/socotecio/django-socio-grpc/blob/master/django_socio_grpc/settings.py#L6
> 
> Please if you try it let me know if it worked. I will still recommend everyone to use a envoy based proxy for performance matter but having multiple choice is always a good thing.
> 
> 
> 
> 

Thank you for the detailed explanation 


I couldn't find documentation for how to setup the envoy proxy with python I would love it if you know one 

And I will try to test Sonora too.

**Comment by AMontagu** [comment]
Here is a docker-compose config:
```
  envoy:
    build:
      context: ./
      dockerfile: ./envoy/Dockerfile
    image: grpcweb/envoy
    volumes:
      - ./envoy:/etc/envoy
    ports:
      - "50001:50001"
    depends_on:
      - docker-running-grpc
    networks:
      network-connected-ro-grpc:
```

here is the docker file:

```
FROM envoyproxy/envoy:v1.17.0

COPY envoy/envoy.yaml /etc/envoy/envoy.yaml

CMD /usr/local/bin/envoy -c /etc/envoy/envoy.yaml -l trace --log-path /tmp/envoy_info.log
```

Here is the envoy configuration:

```
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }

static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 0.0.0.0, port_value: 50001 }
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: { prefix: "/" }
                route:
                  cluster: report-generator-grpc
                  timeout: 0s
                  max_stream_duration:
                    grpc_timeout_header_max: 0s
              cors:
                allow_origin_string_match:
                - prefix: "*"
                allow_methods: GET, PUT, DELETE, POST, OPTIONS
                allow_headers: keep-alive,user-agent,pagination,cache-control,content-type,content-transfer-encoding,custom-header-1,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web,grpc-timeout,filters,headers,
                max_age: "1728000"
                expose_headers: grpc-status,grpc-message,pagination,filters,headers,
          http_filters:
          - name: envoy.filters.http.grpc_web
          - name: envoy.filters.http.cors
          - name: envoy.filters.http.router
  clusters:
  - name: report-generator-grpc
    connect_timeout: 0.25s
    type: logical_dns
    http2_protocol_options: {}
    lb_policy: round_robin
    load_assignment:
      cluster_name: cluster_0
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: docker-running-grpc
                    port_value: 50002

```

Then you have to make sur the conf match (as envoy is a proxy) you need to be sure it is listening on the good port (in example 50001) and sending to the good address and port (in exemple docker-running-grpc on port 50002).

It's just a docker image with config. You can run it in local with docker compose or in kubernetes or any server as long you config are correct.
